version: '3'
networks:
  app:
services:
  api:
    image: "aglanborg/proj-backend:latest"
    container_name: node
    restart: always
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
    networks:
      app:
  client:
    image: "aglanborg/proj-frontend:latest"
    container_name: vue
    ports:
      - '8080:8080'
    depends_on:
      - api
    networks:
      app: